version: '3'

services:
  nginx:
    image: nginx:1.19.0
    ports:
      - "80:80"
    depends_on:
      - wordpress1
      - wordpress2
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - internal_network
    extra_hosts:
      - "host.docker.internal:host-gateway"

  wordpress1:
    image: wordpress:5.4.2-php7.2-apache
    depends_on:
      - mysql
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: example
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - internal_network
      - mysql_network

  wordpress2:
    image: wordpress:5.4.2-php7.2-apache
    depends_on:
      - mysql
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: example
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - internal_network
      - mysql_network

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: wordpress
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - mysql_network

  locust:
      image: grubykarol/locust
      environment:
        - ATTACKED_HOST=http://nginx:80
      volumes:
        - ./path/to/locust-scripts:/locust
      ports:
        - "8089:8089"
      networks:
        - internal_network
        
networks:
  internal_network:
    driver: bridge
  mysql_network:
    driver: bridge

volumes:
  wordpress_data:
  mysql_data:

